version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "exercise-challenge-back-end"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-h7wu99b350u0"
s3_prefix = "exercise-challenge-back-end"
region = "eu-west-1"
profile = "exercise-challenge-admin"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
