# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  A SAM Application which forms part of the Exercise Challenge App

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"
# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # ADMIN CLUSTER
  # Lambda function to create an exercise in the exercises table

  createChallengeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/AdminCluster/create-challenge.createChallengeHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description:
        A simple example includes a HTTP get method to get all items from a
        DynamoDB table.
      Policies:
        - S3WritePolicy:
            BucketName: !Ref ChallengeBucket
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          CHALLENGE_BUCKET: !Ref ChallengeBucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /admin/create-challenge
            Method: POST

  getUsersList:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/AdminCluster/get-users.getUsersHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description:
        A simple example includes a HTTP get method to get all items from a
        DynamoDB table.
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: "2012-10-17" # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:ListUsers
              Resource: "arn:aws:cognito-idp:eu-west-1:398469193293:userpool/eu-west-1_9JNiGMW1S"
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          USER_POOL_ID: eu-west-1_9JNiGMW1S
      Events:
        Api:
          Type: Api
          Properties:
            Path: /admin/get-users
            Method: GET

  getChallengesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/AdminCluster/get-challenges.getChallengesHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description:
        A simple example includes a HTTP get method to get all items from a
        DynamoDB table.
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref ChallengeBucket
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          CHALLENGE_BUCKET: !Ref ChallengeBucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /admin/get-challenges
            Method: GET

  getChallengeDetailsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/AdminCluster/get-challenge-details.getChallengeDetailsHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description:
        A simple example includes a HTTP get method to get all items from a
        DynamoDB table.
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref ChallengeBucket
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          CHALLENGE_BUCKET: !Ref ChallengeBucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /admin/get-challenge-details
            Method: GET

  #USER CLUSTER
  # Lambda function to check the next order number
  getMyExercisesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/UserCluster/get-my-exercises.getMyExercisesHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description:
        A simple example includes a HTTP get method to get all items from a
        DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the OrderCountTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserExerciseTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          USER_EXERCISE_TABLE: !Ref UserExerciseTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /user/get-my-exercise
            Method: GET

  getTeamExerciseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/UserCluster/get-team-exercise.getTeamExerciseHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description:
        A simple example includes a HTTP get method to get all items from a
        DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the OrderCountTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserExerciseTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          USER_EXERCISE_TABLE: !Ref UserExerciseTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /user/get-team-exercise
            Method: GET

  getAllExerciseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/UserCluster/get-all-excercise.getAllExerciseHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description:
        A simple example includes a HTTP get method to get all items from a
        DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the OrderCountTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserExerciseTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          USER_EXERCISE_TABLE: !Ref UserExerciseTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /user/get-all-exercise
            Method: GET

  getExercisesListFuntion:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/UserCluster/get-exercises-list.getExercisesListHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description:
        A simple example includes a HTTP get method to get all items from a
        DynamoDB table.
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref ExerciseListBucket
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          EXERCISE_LIST_BUCKET: !Ref ExerciseListBucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /user/get-exercises-list
            Method: GET

  deleteExerciseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/UserCluster/delete-exercise.deleteExerciseHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description:
        A simple example includes a HTTP get method to get all items from a
        DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the OrderCountTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserExerciseTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          USER_EXERCISE_TABLE: !Ref UserExerciseTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /user/delete-exercise
            Method: POST

  addExerciseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/UserCluster/add-exercise.addExerciseHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description:
        A simple example includes a HTTP get method to get all items from a
        DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserExerciseTable
        - S3ReadPolicy:
            BucketName: !Ref ExerciseListBucket
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          USER_EXERCISE_TABLE: !Ref UserExerciseTable
          EXERCISE_LIST_BUCKET: !Ref ExerciseListBucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /user/add-exercise
            Method: POST

  getLeaguesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/UserCluster/get-league.getLeagueHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description:
        A simple example includes a HTTP get method to get all items from a
        DynamoDB table.
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref LeagueBucket
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          LEAGUE_BUCKET: !Ref LeagueBucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /user/get-league
            Method: GET

  # WORKER CLUSTER
  generateLeaguesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/WorkerCluster/generate-leagues.generateLeagueHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description:
        A simple example includes a HTTP get method to get all items from a
        DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserExerciseTable
        - S3ReadPolicy:
            BucketName: !Ref ChallengeBucket
        - S3WritePolicy:
            BucketName: !Ref LeagueBucket
        - S3ReadPolicy:
            BucketName: !Ref LeagueBucket
        - S3ReadPolicy:
            BucketName: !Ref ExerciseListBucket
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          USER_EXERCISE_TABLE: !Ref UserExerciseTable
          CHALLENGE_BUCKET: !Ref ChallengeBucket
          LEAGUE_BUCKET: !Ref LeagueBucket

  updateLeaguesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/WorkerCluster/update-leagues.updateLeagueHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description:
        A simple example includes a HTTP get method to get all items from a
        DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserExerciseTable
        - S3ReadPolicy:
            BucketName: !Ref ChallengeBucket
        - S3WritePolicy:
            BucketName: !Ref LeagueBucket
        - S3ReadPolicy:
            BucketName: !Ref LeagueBucket
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          USER_EXERCISE_TABLE: !Ref UserExerciseTable
          CHALLENGE_BUCKET: !Ref ChallengeBucket
          LEAGUE_BUCKET: !Ref LeagueBucket

  # References

  UserExerciseTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  ChallengeBucket:
    Type: AWS::S3::Bucket

  LeagueBucket:
    Type: AWS::S3::Bucket

  ExerciseListBucket:
    Type: AWS::S3::Bucket

# Outputs

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
