name: Back-End Production Build
on:
  push:
    branches:
      - main
    paths:
      - "back-end/**"
      - ".github"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-west-1"
      # sam build
      - name: Build
        run: sam build --use-container --template-file ./back-end/template.yaml

      # sam deploy
      - name: Deploy
        run:
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
          --stack-name exercise-challenge-back-end --s3-bucket
          exercise-challenge-back-end-production --capabilities CAPABILITY_IAM
          --region eu-west-1
